In [7]:
import pandas as pd
import numpy as np

In [8]:
features = ['name', 'age', 'species', 'ocupation', 'appearance', 'description']
values = [['Felipe', 38, 'Humano', 'G', 'Brazil', ''],
          ['Totó', 2, 'Chiwalwa', 'P', 'Jamaica', ''],
          ['Johnzinho', 9, 'ET', 'P', 'Brazil', ''],
          ['Totó', 9, 'Doguinho', 'M', 'Brazil', ''],
          ['Satanás', 18, 'Doguinho', 'G', 'Brazil', ''],
          ['Satanás', 18, 'Doguinho', 'G', 'Brazil', ''],
          ['Belinha', 38, 'Chiwalwa', 'P', 'Brazil', ''],
          ['Totó', 2, 'Chiwalwa', 'P', 'Jamaica', ''],
          ['Jericó', 12, 'ET', 'P', 'Brazil', ''],
          ['Maninha', 8, 'Anja', 'P', 'Jamaica', ''],
          ['Tereza', 7, 'Anja', 'P', 'Jamaica', ''],
          ['Dona Benta', 8, 'Anja', 'P', 'Jamaica', ''],
          ['Gunter', 1.38e10, 'Cosmic Entity', 'servant', '1, 2, 3', 'Gunter is the penguin that most commonly accompanies the Ice King. The Ice King uses Gunter as his personal servant, whereas the other penguins working for The Ice King are essentialy slaves.'],
          ['The Lich', 1.38e10, 'Cosmic Entity', 'sorcerer', '1, 2, 3', 'The Lich is an ancient cosmic being who is the manifestation']
          ]

df = pd.DataFrame(values, columns=features)

df

,name,age,species,ocupation,appearance,description
0,Felipe,3.800000e+01,Humano,G,Brazil,
1,Totó,2.000000e+00,Chiwalwa,P,Jamaica,
2,Johnzinho,9.000000e+00,ET,P,Brazil,
3,Totó,9.000000e+00,Doguinho,M,Brazil,
4,Satanás,1.800000e+01,Doguinho,G,Brazil,
5,Satanás,1.800000e+01,Doguinho,G,Brazil,
6,Belinha,3.800000e+01,Chiwalwa,P,Brazil,
7,Totó,2.000000e+00,Chiwalwa,P,Jamaica,
8,Jericó,1.200000e+01,ET,P,Brazil,
9,Maninha,8.000000e+00,Anja,P,Jamaica,
10,Tereza,7.000000e+00,Anja,P,Jamaica,
11,Dona Benta,8.000000e+00,Anja,P,Jamaica,
12,Gunter,1.380000e+10,Cosmic Entity,servant,"1, 2, 3",Gunter is the penguin that most commonly accom...
13,The Lich,1.380000e+10,Cosmic Entity,sorcerer,"1, 2, 3",The Lich is an ancient cosmic being who is the...

In [13]:
my_new_df = df.set_index('name')
my_new_df

,age,species,ocupation,appearance,description
name,,,,,
Felipe,3.800000e+01,Humano,G,Brazil,
Totó,2.000000e+00,Chiwalwa,P,Jamaica,
Johnzinho,9.000000e+00,ET,P,Brazil,
Totó,9.000000e+00,Doguinho,M,Brazil,
Satanás,1.800000e+01,Doguinho,G,Brazil,
Satanás,1.800000e+01,Doguinho,G,Brazil,
Belinha,3.800000e+01,Chiwalwa,P,Brazil,
Totó,2.000000e+00,Chiwalwa,P,Jamaica,
Jericó,1.200000e+01,ET,P,Brazil,
Maninha,8.000000e+00,Anja,P,Jamaica,
Tereza,7.000000e+00,Anja,P,Jamaica,
Dona Benta,8.000000e+00,Anja,P,Jamaica,
Gunter,1.380000e+10,Cosmic Entity,servant,"1, 2, 3",Gunter is the penguin that most commonly accom...
The Lich,1.380000e+10,Cosmic Entity,sorcerer,"1, 2, 3",The Lich is an ancient cosmic being who is the...

In [15]:
print(my_new_df.loc['The Lich'])

age                                                13800000000.0
species                                            Cosmic Entity
ocupation                                               sorcerer
appearance                                               1, 2, 3
description    The Lich is an ancient cosmic being who is the...
Name: The Lich, dtype: object